/**
 * Builds a small, valid one-page PDF invoice, so the sample data has real
 * bills that open in any PDF viewer. Hand-written PDF objects with a correct
 * cross-reference table; Helvetica only, so text is limited to Latin-1.
 */
export interface SampleBill {
  store: string
  invoiceNo: string
  date: string
  lines: [string, string][]
  total: string
  footer: string
}

const pdfText = (s: string) => s.replace(/[^\x20-\x7e]/g, '-').replace(/([\\()])/g, '\\$1')

export function samplePdfBase64(bill: SampleBill): string {
  const ops: string[] = ['0.93 0.95 0.94 rg 0 742 595 100 re f', '0.05 0.2 0.16 rg']
  const text = (x: number, y: number, size: number, s: string, bold = false) => ops.push(`BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${pdfText(s)}) Tj ET`)
  text(48, 790, 20, bill.store, true)
  text(48, 766, 10, 'SAMPLE INVOICE')
  text(400, 790, 10, `Invoice: ${bill.invoiceNo}`)
  text(400, 774, 10, `Date: ${bill.date}`)
  let y = 700
  text(48, y, 10, 'Item', true)
  text(470, y, 10, 'Amount', true)
  ops.push(`0.7 0.75 0.72 RG 48 ${y - 8} m 547 ${y - 8} l S`)
  for (const [label, amount] of bill.lines) {
    y -= 24
    text(48, y, 11, label)
    text(470, y, 11, amount)
  }
  y -= 20
  ops.push(`48 ${y} m 547 ${y} l S`)
  y -= 22
  text(370, y, 12, 'Total', true)
  text(470, y, 12, bill.total, true)
  text(48, 80, 9, bill.footer)
  text(48, 64, 8, 'Sample bill generated by Covered for the demo. Not a real invoice.')
  const stream = ops.join('\n')

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ]
  let pdf = '%PDF-1.4\n'
  const offsets: number[] = []
  objects.forEach((body, i) => {
    offsets.push(pdf.length)
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`
  })
  const xref = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const o of offsets) pdf += `${String(o).padStart(10, '0')} 00000 n \n`
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`
  // ASCII only, so btoa is safe in both Node and browsers.
  return btoa(pdf)
}
