import { expect, test } from '@playwright/test'
import { exploreSample, saveScore, signUp, startCrew } from './helpers.ts'

test.describe('Couch Cup (static demo build)', () => {
  test('a whole cup night: crew, bracket, extra time, shoot-out, champion', async ({ page }) => {
    await signUp(page, 'Piyush')
    await startCrew(page, 'Saturday Cup', ['Rohan', 'Aisha', 'Kabir'])
    await page.getByRole('button', { name: 'New competition' }).first().click()
    const d = page.getByRole('dialog', { name: 'New competition' })
    await d.getByLabel('Name').fill('Saturday Cup')
    await d.getByText('Knockout cup').click()
    await d.getByRole('radio', { name: 'As listed' }).click()
    await expect(d.getByText('A 4-player bracket: 3 matches.')).toBeVisible()
    await d.getByRole('button', { name: 'Create & draw fixtures' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Saturday Cup' })).toBeVisible()

    const bracket = page.getByRole('list', { name: 'Bracket' })
    // Semi 1: Piyush v Kabir, won in extra time.
    await bracket.getByRole('button', { name: /Semi-finals: Piyush vs Kabir/ }).click()
    let dialog = page.getByRole('dialog', { name: 'Enter result' })
    await dialog.getByRole('radio', { name: 'After extra time' }).click()
    await saveScore(dialog, 2, 1)
    // Semi 2: Rohan v Aisha, level — needs a shoot-out.
    await bracket.getByRole('button', { name: /Semi-finals: Rohan vs Aisha/ }).click()
    dialog = page.getByRole('dialog', { name: 'Enter result' })
    await dialog.getByRole('spinbutton').nth(0).fill('1')
    await dialog.getByRole('spinbutton').nth(1).fill('1')
    await expect(dialog.getByText("It's level — a knockout needs a winner. Choose Penalties.")).toBeVisible()
    await dialog.getByRole('radio', { name: 'Penalties' }).click()
    await dialog.getByRole('spinbutton', { name: 'Rohan penalties' }).fill('3')
    await dialog.getByRole('spinbutton', { name: 'Aisha penalties' }).fill('4')
    await dialog.getByRole('button', { name: 'Save result' }).click()
    await expect(dialog).toBeHidden()

    // Final: Piyush v Aisha.
    await bracket.getByRole('button', { name: /Final: Piyush vs Aisha/ }).click()
    await saveScore(page.getByRole('dialog', { name: 'Enter result' }), 3, 0)
    await expect(page.getByRole('region', { name: 'Champion' })).toContainText('Piyush')
    await expect(bracket.getByRole('button', { name: /Semi-finals: Rohan 1–1 Aisha, 3–4 on penalties/ })).toBeVisible()

    // The crew page reflects it all.
    await page.getByRole('link', { name: 'Saturday Cup' }).first().click()
    await page.getByRole('tab', { name: 'Overview' }).click()
    await expect(page.getByRole('region', { name: 'Power rankings' }).getByRole('listitem').first()).toContainText('Piyush')
  })

  test('changing an earlier knockout result is blocked once the next round is played', async ({ page }) => {
    await signUp(page, 'Meera')
    await startCrew(page, 'Strict Cup', ['Rohan', 'Aisha', 'Kabir'])
    await page.getByRole('button', { name: 'New competition' }).first().click()
    const d = page.getByRole('dialog', { name: 'New competition' })
    await d.getByLabel('Name').fill('Strict Cup')
    await d.getByText('Knockout cup').click()
    await d.getByRole('radio', { name: 'As listed' }).click()
    await d.getByRole('button', { name: 'Create & draw fixtures' }).click()
    const bracket = page.getByRole('list', { name: 'Bracket' })
    await bracket.getByRole('button', { name: /Semi-finals: Meera vs Kabir/ }).click()
    await saveScore(page.getByRole('dialog', { name: 'Enter result' }), 1, 0)
    await bracket.getByRole('button', { name: /Semi-finals: Rohan vs Aisha/ }).click()
    await saveScore(page.getByRole('dialog', { name: 'Enter result' }), 1, 0)
    await bracket.getByRole('button', { name: /Final: Meera vs Rohan/ }).click()
    await saveScore(page.getByRole('dialog', { name: 'Enter result' }), 2, 2 + 1)
    await bracket.getByRole('button', { name: /Semi-finals: Meera 1–0 Kabir/ }).click()
    const dialog = page.getByRole('dialog', { name: 'Edit result' })
    await dialog.getByRole('spinbutton').nth(1).fill('2')
    await dialog.getByRole('button', { name: 'Save result' }).click()
    await expect(dialog.getByText(/Clear the Final result first/)).toBeVisible()
  })

  test('invite link: a second account on this device claims a player and keeps their results', async ({ page }) => {
    await exploreSample(page)
    await page.getByRole('tab', { name: 'Players' }).click()
    const code = (await page.getByLabel(/^Invite code/).textContent())!.trim()
    await page.getByRole('button', { name: /Account menu/ }).click()
    await page.getByRole('menuitem', { name: 'Sign out' }).click()
    await signUp(page, 'Rohan')
    await page.goto(`./#/join/${code}`)
    await page.getByRole('radio', { name: "I'm Rohan" }).check()
    await page.getByRole('button', { name: 'Join crew' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Hostel Room 12' })).toBeVisible()
    await expect(page.getByText('Your rating').locator('..')).toContainText('#1 of 6')
  })

  test('player pages, head-to-heads and deep links survive a reload', async ({ page }) => {
    await exploreSample(page)
    await page.getByRole('region', { name: 'Power rankings' }).getByRole('link', { name: 'Rohan' }).click()
    await expect(page.getByRole('heading', { level: 1, name: /Rohan/ })).toBeVisible()
    await expect(page.getByRole('img', { name: /Rohan's rating over \d+ matches/ })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Rating history' })).toBeVisible()
    await page.goBack()
    await page.getByRole('tab', { name: 'Head-to-head' }).click()
    await page.getByRole('combobox', { name: 'Second player' }).selectOption({ label: 'Rohan' })
    await expect(page.getByRole('region', { name: 'Head to head' })).toContainText(/Demo wins/)
  })

  test('works on a phone without sideways scrolling', async ({ browser }) => {
    const ctx = await browser.newContext({ viewport: { width: 375, height: 740 }, hasTouch: true, isMobile: true })
    const page = await ctx.newPage()
    await exploreSample(page)
    const noOverflow = () => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)
    expect(await noOverflow()).toBe(true)
    await expect(page.getByRole('navigation', { name: 'Main' })).toBeVisible()
    await page.getByRole('button', { name: 'Play a friendly' }).first().click()
    await expect(page.getByRole('dialog', { name: 'Play a friendly' })).toBeVisible()
    expect(await noOverflow()).toBe(true)
    await page.keyboard.press('Escape')
    await page.getByRole('tab', { name: 'Competitions' }).click()
    await page.getByRole('link', { name: /Diwali Cup/ }).click()
    await expect(page.getByRole('list', { name: 'Bracket' })).toBeVisible()
    expect(await noOverflow()).toBe(true) // the bracket scrolls inside its card, not the page
    await page.goBack()
    await page.getByRole('link', { name: /Season 1/ }).click()
    await expect(page.getByRole('table', { name: 'Season 1 table' })).toBeVisible()
    expect(await noOverflow()).toBe(true)
    await ctx.close()
  })
})
